[build]
  publish = "dist"                                                                                                                                   
  command = "npm run build"                    
  functions = "functions/dist"
  
[[redirects]]
  from = "/"
  to = "/db.json"
  status = 302
